# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c20656a2c94eec82fb9cd1aac5fd5f9d2ea81601ce01582ba81282ef177647a9148fe68cedb99beb84f63c01bc6c9a9f80989db7d8db4e616dbaba609d365ab1

test:
  secret_key_base: 31fa4c188bda71c9aee3ab6011d2ba6f9b0387a4ca8d24441ee605edfd6f2a6dfdaa6b69d7c8a5b9d7d785f5ce3d8a57abfaa7972161909f3016b6984dafa38a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
